# Install script for directory: /home/ubuntu/zephyrproject/zephyr

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Debug")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/home/ubuntu/zephyr-sdk-fake/sysroots/aarch64-pokysdk-linux/usr/bin/objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/zephyr/arch/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/zephyr/lib/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/zephyr/soc/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/zephyr/boards/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/zephyr/subsys/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/zephyr/drivers/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/acpica/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/cmsis/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/cmsis-dsp/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/cmsis-nn/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/fatfs/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/altera/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hal_ambiq/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/atmel/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hal_espressif/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hal_ethos_u/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hal_gigadevice/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hal_infineon/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hal_intel/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/microchip/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hal_nordic/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/nuvoton/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hal_nxp/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/openisa/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/quicklogic/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hal_renesas/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hal_rpi_pico/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/silabs/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hal_st/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/stm32/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hal_telink/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/ti/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hal_wurthelektronik/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/xtensa/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/hostap/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/libmetal/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/liblc3/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/littlefs/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/loramac-node/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/lvgl/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/mbedtls/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/mcuboot/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/mipi-sys-t/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/nrf_hw_models/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/open-amp/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/openthread/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/percepio/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/picolibc/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/segger/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/tinycrypt/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/trusted-firmware-m/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/trusted-firmware-a/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/uoscore-uedhoc/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/modules/zcbor/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/zephyr/kernel/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/zephyr/cmake/flash/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/zephyr/cmake/usage/cmake_install.cmake")
  include("/home/ubuntu/PQ-EDHOC/build_ops_runtime/type0-classic-initiator/zephyr/cmake/reports/cmake_install.cmake")

endif()

